// <auto-generated />
using System;
using EF_Core.Transactions.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Transaction.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251110164121_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EF_Core.Transactions.Entities.BankAccount", b =>
                {
                    b.Property<string>("AccountId")
                        .HasMaxLength(20)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("AccountHolder")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("CurrentBalance")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("AccountId");

                    b.ToTable("BankAccounts", (string)null);
                });

            modelBuilder.Entity("EF_Core.Transactions.Entities.GLTransaction", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("BankAccountAccountId")
                        .HasColumnType("VARCHAR(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR");

                    b.HasKey("Id");

                    b.HasIndex("BankAccountAccountId");

                    b.ToTable("GLTransactions", (string)null);
                });

            modelBuilder.Entity("EF_Core.Transactions.Entities.GLTransaction", b =>
                {
                    b.HasOne("EF_Core.Transactions.Entities.BankAccount", null)
                        .WithMany("GLTransactions")
                        .HasForeignKey("BankAccountAccountId");
                });

            modelBuilder.Entity("EF_Core.Transactions.Entities.BankAccount", b =>
                {
                    b.Navigation("GLTransactions");
                });
#pragma warning restore 612, 618
        }
    }
}
