@baseUrl = https://localhost:7194

@productId = 2779ee47-10b0-4bd7-8342-404006aa1392
# @productId = 1a2b3c4d-5e6f-7a8b-9c0d-890abcdef123
 
###
GET {{baseUrl}}/api/products?page=1&pageSize=100

###
GET {{baseUrl}}/api/products/{{productId}}?includeReviews=true

### 
POST {{baseUrl}}/api/products
Content-Type: application/json

{
  "name": "IPhone 17",
  "price": 499.99
}


###
POST {{baseUrl}}/api/products/{{productId}}/reviews
Content-Type: application/json

{
  "reviewer": "Kevin Kelo",
  "stars": 3
}

### 
PUT {{baseUrl}}/api/products/{{productId}}
Content-Type: application/json

{
    "name": "chocolate bar",
    "price": 3.50
}

### DELETE
DELETE {{baseUrl}}/api/products/{{productId}}
