@baseUrl = https://localhost:7179

//=================================================
//=========== Minimal API =========================
//=================================================

### 
GET {{baseUrl}}/product-minimal
X-Api-Version: v1
language: Arabic


//=================================================
//=========== Controllers =========================
//=================================================

### 
GET {{baseUrl}}/product-controller
X-Api-Version: v2
language: English

