@baseUrl = https://localhost:7179

//=================================================
//=========== Minimal API =========================
//=================================================

###
GET {{baseUrl}}/cookie-minimal
Cookie: session-id=xyz789

//=================================================
//=========== Controllers =========================
//=================================================

###
GET {{baseUrl}}/cookie-controller
Cookie: session-id=xyz789
