@baseUrl = https://localhost:9191

###
GET {{baseUrl}}/api/bids

###
GET {{baseUrl}}/api/bids/128a65fb-d494-45de-9248-8c135b5b41ed

###
POST {{baseUrl}}/api/bids
content-type: application/json

{
  "amount": 150.00,
  "firstName": "John",
  "lastName": "Doe",
  "email": "john.doe@example.com",
  "telephone": "+1234567890",
  "location": "Amman",
  "address": "123 Rainbow Street"
}
