@baseUrl = https://localhost:7107/api/controller-fake-errors


### Root
GET {{baseUrl}}

// ========================================================

### Server Error
GET {{baseUrl}}/server-error

// ========================================================

### Bad Request without Body
POST {{baseUrl}}/bad-request
Content-Type: application/json

### Bad Request with Body
POST {{baseUrl}}/bad-request-1
Content-Type: application/json

### Bad Request + Problem
POST {{baseUrl}}/bad-request-2
Content-Type: application/json

// ========================================================

### Not Found without Body
POST {{baseUrl}}/not-found
Content-Type: application/json

### Not Found with Body
POST {{baseUrl}}/not-found-1
Content-Type: application/json

### Not Found + Problem
POST {{baseUrl}}/not-found-2
Content-Type: application/json

// ========================================================

### Conflict without Body
POST {{baseUrl}}/conflict
Content-Type: application/json

### Conflict with Body
POST {{baseUrl}}/conflict-1
Content-Type: application/json

### Conflict + Problem
POST {{baseUrl}}/conflict-2
Content-Type: application/json

// ========================================================

### Unauthorized without Body
POST {{baseUrl}}/unauthorized
Content-Type: application/json

### Unauthorized with Body
POST {{baseUrl}}/unauthorized-1
Content-Type: application/json

### Unauthorized + ProblemDetails
POST {{baseUrl}}/unauthorized-2
Content-Type: application/json

// ========================================================

### Business Rule Error
POST {{baseUrl}}/business-rule-error
Content-Type: application/json
