@baseUrl = https://localhost:7286
@productId = 2779ee47-10b0-4bd7-8342-404006aa1392


### old way (version 1)
GET {{baseUrl}}/api/products/{{productId}}


### version 1
GET {{baseUrl}}/api/v1.0/products/{{productId}}


### version 2
GET {{baseUrl}}/api/v2.0/products/{{productId}}

